version: 2.1
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker: 
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: 
          name: build api-test
          command: |
            cd rambutan-api-test
            ./gradlew clean build -x test
      - run:
          name: run API tests
          command: |
            cd rambutan-api-test
            ./gradlew test -i
      - store_test_results:
          path: build/test-results/test
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: build/test-results/test
          when: always
        